### ISSUE TITLE
FileNotFoundException: https://mydomain.com:8443/cas/login/p3/serviceValidate?ticket=

### ISSUE THREAD

**Issue by gabouy** [UniconLabs/cas-sample-java-webapp#10]
Hi,

I'm attempting to run this sample webapp with a CAS 6.0.0-RC1 installation I have setup in another node.

I've configured the web.xml to target my CAS installation and started the webapp according to the README instructions. 

When browsing this sample app I'm redirected to the CAS login, I enter my credentials, and then the following error is displayed.

```
HTTP ERROR 500
Problem accessing /sample/. Reason:

    Server Error
Caused by:
java.lang.RuntimeException: java.io.FileNotFoundException: https://mydomain.com:8443/cas/login/p3/serviceValidate?ticket=ST-3-ppf6QjykhqFHGczk24CiyBgJ7sQip-XXX-XX-XX-XX&service=https%3A%2F%2Fmydomain.com%3A9443%2Fsample%2F&authn_method=mfa-duo
	at org.jasig.cas.client.util.CommonUtils.getResponseFromServer(CommonUtils.java:443)
	at org.jasig.cas.client.validation.AbstractCasProtocolUrlBasedTicketValidator.retrieveResponseFromServer(AbstractCasProtocolUrlBasedTicketValidator.java:41)
	at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:193)
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:204)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:97)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```
Any hints/pointers as to what should be done to fix this are appreciated.

thanks!

**Comment by mmoayyed** [comment]
This:

```
https://mydomain.com:8443/cas/login/p3/serviceValidate
```

Should be:

```
https://mydomain.com:8443/cas/p3/serviceValidate
```

**Comment by kritipchakrabarti** [comment]
### @mmoayyed @gabouy 

Is this issue still open. I can contribute on this.
